#coding=UTF-8
ruleDatas = {
    #   指纹格式请严格遵守如下格式
    #   多个匹配特征在小括号内用 | 分割，比如下边 “Tomcat默认页面” 这个
    #  '应用名称':{'value':'小写应用关键描述','finger':'(匹配关键字)'},

    ###高危中间件
    'Shiro框架':{'value':'shiro','finger':'(deleteMe)'},
    'Weblogic':{'value':'weblogic','finger':'(Hypertext Transfer Protocol -- HTTP/1.1</i>)'},
    'Jboss':{'value':'jboss','finger':'(jboss.css)'},
    'Tomcat默认页面':{'value':'tomcat','finger':'(/manager/html|/manager/status)'},
    'Spring框架':{'value':'spring','finger':'(116323821)'},

    #协同办公
    '致远OA':{'value':'seeyon','finger':'(/seeyon/USER-DATA/IMAGES/LOGIN/login.gif|/seeyon/common|SY8045|Seeyon-Server/1.0|yyoa/)'},
    '通达OA':{'value':'tongda','finger':'(tongda.ico|onmouseover="this.focus()")'},
    '泛微OA':{'value':'ecology','finger':'(/wui/theme|/js/ecology8/lang/weaver_lang_7_wev8.js|WVS)'},
    'e-Bridge':{'value':'e-bridge','finger':'(/main/login/images/loginlogo.png|e-Bridge)'},
    'E-Mobile':{'value':'e-mobile','finger':'(weaver,e-mobile|E-Mobile&nbsp;)'},
    '蓝凌OA':{'value':'landray','finger':'(kmss_onsubmit|sys/ui/extend/theme/default/style/icon.css)'},
    '用友软件':{'value':'yongyou','finger':'(uclient.yonyou.com)'},
    'Zentao-禅道':{'value':'zentao','finger':'(zentaosid|/zentao/js|/zentao/theme/|/theme/default/images/main/zt-logo.png)'},
    '协众OA':{'value':'xiezhong','finger':'(CNOAOASESSID|Powered by 协众OA)'},
    '金和OA':{'value':'jinheoa','finger':'(金和协同管理平台)'},
    '金碟EAS':{'value':'kdgs','finger':'(easSessionId)'},
    '金碟政务GSiS':{'value':'kdgs','finger':'(/kdgs/script/kdgs.js)'},

    ###内容管理CMS
    'WordPress':{'value':'wordpress','finger':'(wp-content)'},
    'ThinkCMF':{'value':'thinkcmf','finger':'({Simple content manage Framework)'},
    'ThinkPHP':{'value':'thinkphp','finger':'(ThinkPHP</a>|十年磨一剑-为API开发设计的高性能框架|<h1>页面错误！请稍后再试～</h1>)'},
    'ThinkPHP-3.x':{'value':'thinkphp3','finger':'(Simple OOP PHP Framework)'},
    'Spring-Boot':{'value':'springboot','finger':'(<title>Spring Boot开发平台</title>)'},


    ###邮件服务器
    'Exchange':{'value':'exchange','finger':'(/owa/auth.owa)'},
    'CoreMail':{'value':'coremail','finger':'(coremail/common)'},

    ###网站管理 集群、监控、仓库、队列 、大数据
    'Swagger-UI':{'value':'swaggerui','finger':'(/swagger-ui.css|swagger-ui-bundle.js)'},
    'Gitlab':{'value':'gitlab','finger':'(assets/gitlab_logo|GitLab</title>)'},
    '宝塔面板':{'value':'baota','finger':'(app.bt.cn/static/app.png|安全入口校验失败)'},
    'phpMyAdmin':{'value':'phpmyadmin','finger':'(phpmyadmin.css|img/logo_right.png)'},
    'Zabbix':{'value':'zabbix','finger':'(zbx_sessionid|images/general/zabbix.ico|Zabbix SIA)'},
    'Nagios':{'value':'nagios','finger':'(Nagios Access)'},
    'Nexus':{'value':'nexus','finger':'(Nexus Repository Manager|NX-ANTI-CSRF-TOKEN)'},
    'Harbor':{'value':'harbor','finger':'(harbor-lang|<title>Harbor</title>)'},
    'Jenkins':{'value':'jenkins','finger':'(M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z)'},
    'RabbitMQ':{'value':'rabbitmq','finger':'(<title>RabbitMQ Management</title>)'},
    'Jira':{'value':'jira','finger':'(jira.webresources)'},
    'Spark_Master':{'value':'spark','finger':'(Spark Master at)'},
    'Spark_Worke':{'value':'spark','finger':'(Spark Worker at)'},
    'Elasticsearch':{'value':'elasticsearch','finger':'(1611729805)'},
    'XXL-Job':{'value':'xxljob','finger':'(分布式任务调度平台XXL-JOB)'},

    ###绿盟设备
    '绿盟安全审计系统堡垒机 SAS[H]':{'value':'nsfocus-sas[h]','finger':'(/stylesheet/login/images/login-title.png)'},
    '绿盟安全审计系统 SAS':{'value':'nsfocus-sas','finger':'(/stylesheet/nsfocus_2012/images/logo/login_logo_sas_zh_CN.png)'},
    '绿盟下一代防火墙 NF':{'value':'nsfocus-nf','finger':'(/stylesheet/iceye/images/logo/login_logo_nf_zh_CN.png)'},
    '绿盟统一身份认证平台 UIP':{'value':'nsfocus-uip','finger':'(/img/login_logo_auth_zh_CN.jpg|用户认证 - NSFOCUS NF)'},
    '绿盟邮件安全网关 SEG':{'value':'nsfocus-seg','finger':'(/stylesheet/images/login/login_logo.png|SEG NSFOCUS)'},
    '绿盟抗拒绝服务系统 ADS':{'value':'nsfocus-ads','finger':'(/stylesheet/nsfocus_2009/images/logo/login_logo_ads_en_US.png|NSFOCUS ADS)'},
    '绿盟远程安全评估系统 RSAS':{'value':'nsfocus-rsas','finger':'(/media/stylesheet/nsfocus_2012/images/logo/login_logo_rsas_zh_CN.png|NSFOCUS RSAS)'},
    '绿盟网络入侵防护系统 NIPS':{'value':'nsfocus-nips','finger':'(stylesheet/nsfocus_2012/images/logo/login_logo_nips_zh_CN.png)'},
    '绿盟网络入侵检测系统 NIDS':{'value':'nsfocus-nids','finger':'(/stylesheet/nsfocus_2012/images/logo/login_logo_nids_zh_CN.png)'},
    '绿盟互联网威胁检测系统 TDC':{'value':'nsfocus-tdc','finger':'(/stylesheet/nsfocus_2012/images/logo/login_logo_tdc_zh_CN.png)'},
    '绿盟web防护应用系统 WAF':{'value':'nsfocus-waf','finger':'(/stylesheet/nsfocus_2012/images/logo/login_logo_waf2_zh_CN.png)'},
    '绿盟安全配置核查系统 BVS':{'value':'nsfocus-bvs','finger':'(/media/stylesheet/nsfocus_2012/images/logo/login_logo_bvs_zh_CN.png)'},
    '绿盟数据库审计系统 DAS':{'value':'nsfocus-das','finger':'(nsfocus/css/tab_simple.css|NSFOCUS DAS)'},
    '绿盟敏感数据发现与风险评估系统 IDR':{'value':'nsfocus-idr','finger':'(/media/UI3.0/css/login_iscat.css)'},
    '绿盟等保工具箱非法外联信息展示':{'value':'nfdengbaogongju','finger':'(绿盟等保工具箱非法外联信息展示)'},
    '云安全集中管理系统 NCSS':{'value':'nsfocus-ncss','finger':'(styles.ba9cfe607703704e053c.css|绿盟云安全集中管理系统)'},
    '绿盟企业安全中心系统 ESPC':{'value':'nsfocus-espc','finger':'(/resource/v1.0.1/stylesheet/images/logo/login_logo_espc_zh_CN.png|绿盟企业安全中心)'},
    '绿盟安全认证网关 SAG':{'value':'nsfocus-sag','finger':'(styles.ed82806eaa4b1f6c3a24.bundle.css|assets/image/sag.png)'},
    '绿盟综合威胁探针 UTS':{'value':'nsfocus-uts','finger':'(UTS 综合威胁探针)'},
    '绿盟网站安全监测系统 WSM':{'value':'nsfocus-wsm','finger':'(/medias/stylesheet//nsfocus_2009/images/logo/login_logo_wsm_zh_CN.png)'},


    ###天融信设备
    '天融信入侵防御系统 TopIDP':{'value':'topidp','finger':'(天融信入侵防御系统TopIDP)'},
    '天融信VPN':{'value':'topvpn','finger':'(vone/pub/common/css/sv_login_style_ie9.css)'},
    '天融信认证客户端':{'value':'toprenzheng','finger':'(BODY leftmargin="0" topmargin="0" onbeforeunload="closeDep()")'},
    '天融信Web应用安全防护系统TopWaf':{'value':'topwaf','finger':'(WEB应用安全防护系统)'},
    '天融信入侵检测系统TopSentry':{'value':'topsentry','finger':'(天融信入侵检测系统TopSentry)'},
    '天融信入侵防御系统V3':{'value':'topidpv3','finger':'(天融信入侵防御系统V3（木马监控系统）)'},
    '天融信病毒网关系统':{'value':'topfangbingdu','finger':'(var theform = document.forms["theForm"]; theForm.username.focus();)'},
    '天融信负载均衡系统TopApp':{'value':'topapp','finger':'(TopAPP负载均衡系统)'},
    '天融信负载均衡系统TopApp-LB':{'value':'topapp-lb','finger':'(TopApp-LB 负载均衡系统)'},
    '天融信接入网关系统':{'value':'topjieruwangguan','finger':'(天融信接入网关系统)'},
    '天融信数据防泄漏系统':{'value':'topshujufangxielou','finger':'(天融信数据防泄漏系统|天融信 - Trial)'},

    ###深信服设备
    'Sangfor-深信服VPN':{'value':'sangfor-vpn','finger':'(login_psw.csp|loginPageSP/loginPrivacy.js)'},
    'Sangfor-深信服上网行为管理':{'value':'sangfor-uac','finger':'(utccjfaewjb)'},
    'Sangfor-深信服应用交付报表系统':{'value':'zhifubaobiao','finger':'(report/js/prng4.js|/reportCenter/index.php?cls_mode=cluster_mode_others)'},
    'Sangfor-深信服WAF':{'value':'WAF','finger':'(commonFunction.js)'},
    'Sangfor-深信服防火墙NGAF':{'value':'NGAF','finger':'(SANGFOR FW)'},
    '深信服虚拟化管理平台':{'value':'xunihuaguanli','finger':'(home/mod-login/img/icon-title-adesk.png)'},
    '深信服数据中心':{'value':'shujuzhongxin','finger':'(SANGFOR 数据中心|src/images/login/product_logo.png)'},
    '深信服基线核查系统':{'value':'jixianhecha','finger':'(SMC/images/login/login-bg2.jpg)'},
    '深信服安全隔离与交换系统':{'value':'gelijiaohuan','finger':'(common/slg/img/product_logo.png)'},
    '深信服一体化网关MIG':{'value':'MIG','finger':'(一体化网关MIG)'},
    '深信服行为感知系统【日志中心】':{'value':'xingweiganzhi','finger':'(isHighPerformance : !!SFIsHighPerformance,)'},
    '深信服安全隔离与信息单向导入系统':{'value':'gelidaoru','finger':'(深信服安全隔离与信息单向导入系统)'},
    
    ###合众产品
    '合众视频安全交换接入系统':{'value':'hezhong','finger':'(合众视频安全交换接入系统)'},
    '视频安全接入用户认证系统':{'value':'hezhong','finger':'(视频安全接入用户认证系统)'},
    '合众数据交换控制平台':{'value':'hezhong','finger':'(合众数据交换控制平台)'},
    '边界接入巡检管理系统':{'value':'hezhong','finger':'(边界接入巡检管理系统)'},
    '请求服务系统登录':{'value':'hezhong','finger':'(请求服务系统登录)'},
    '集中监控管理系统':{'value':'hezhong','finger':'(集中监控管理系统)'},
    '安全数据交换系统':{'value':'hezhong','finger':'(安全数据交换系统)'},
    '单向光闸（发送端）——安全管理中心':{'value':'hezhong','finger':'(单向光闸（发送端）——安全管理中心)'},
    '单向光闸——接收端':{'value':'hezhong','finger':'(单向光闸——接收端)'},
    '合众日志采集软件':{'value':'hezhong','finger':'(合众日志采集软件)'},

    ###安恒产品
    '明御安全网关':{'value':'myanquanwangguan','finger':'(明御安全网关)'},
    '明御APT攻击（网络战）预警平台':{'value':'myapt','finger':'(明御APT攻击（网络战）预警平台)'},
    '天鉴流量监测引擎':{'value':'myliuliangjiance','finger':'(天鉴流量监测引擎)'},
    '网站安全检测平台':{'value':'myanquanjiance','finger':'(loadoem?path=login-logo.png)'},
    '明御 运维审计与风险控制系统':{'value':'myyunweishenji','finger':'(明御 运维审计与风险控制系统)'},
    '明御WEB应用防火墙':{'value':'mywaf','finger':'(/images/waf-v.png)'},
    '明御综合日志审计平台':{'value':'myrizhishenji','finger':'(明御综合日志审计平台)'},
    '明御数据库审计与风险控制系统':{'value':'myshujushenji','finger':'(明御数据库审计与风险控制系统)'},

    ###奇安信设备
    '态势感知与安全运营平台':{'value':'taishiganzhi','finger':'(nsgoc)'},
    '奇安信网神智慧防火墙系统':{'value':'fanghuoqiang','finger':'(奇安信网神防火墙系统)'},
    '奇安信统一认证平台':{'value':'tongyirenzheng','finger':'(奇安信统一认证平台)'},
    '奇安信VPN':{'value':'vpn','finger':'(奇安信VPN)'},
    '奇安信天擎终端安全管理系统':{'value':'tianqin','finger':'(奇安信新天擎)'},
    '奇安信网神分析平台':{'value':'fenxi','finger':'(奇安信网神分析平台)'},
    '奇安信网神TrustSpace安全工作空间平台':{'value':'trustspace','finger':'(TrustSpace管理中心)'},
    '奇安信网神网络数据传感器':{'value':'vhuanganqi','finger':'(奇安信网神网络数据传感器)'},
    '奇安信安全大数据管理平台':{'value':'dashuju','finger':'(0x01 应用指纹 · 语雀.html)'},
    '奇安信天眼下一代威胁感知系统(天眼)':{'value':'tianyan','finger':'(奇安信网神全流量威胁发现系统|奇安信天眼分析平台)'},
    '奇安信网神SecFox日志收集与分析系统':{'value':'secfox','finger':'(LAS)'},
    '奇安信网神代码卫士系统':{'value':'daimaweishi','finger':'(奇安信网神代码卫士系统)'},
    '奇安信网神行为感知分析系统':{'value':'ganzhifenxi','finger':'(行为感知分析系统-奇安信)'},
    '奇安信全球鹰网站云检测系统':{'value':'yunjiance','finger':'(奇安信网站云监测)'},
    '奇安信网神安全网络路由网关':{'value':'luyou','finger':'(奇安信网神安全网络路由网关系统)'},
    '奇安信云手机':{'value':'yunshouji','finger':'(奇安信云手机管理平台)'},
    '奇安信网神上网行为管理与审计系统':{'value':'wangshen','finger':'(奇安信网神上网行为管理与审计系统)'},
    '奇安信网神互联网接入口检测器系统':{'value':'jianceqi','finger':'(奇安信网神互联网接入口检测器系统)'},
    '奇安信网神安全资产管理系统':{'value':'anquanzichan','finger':'(奇安信网神资产管理系统)'},
    '奇安信移动应用自防护系统':{'value':'yidongyingyong','finger':'(MIAP管理中心)'},
    '天机移动终端安全管理系统':{'value':'tianji','finger':'(奇安信天机管理中心|TrustSpace管理中心)'},
    '奇安信网神VPN安全网关系统':{'value':'anquanwangguan','finger':'(网神VPN安全网关系统)'},
    '奇安信代码卫士':{'value':'daimaweishi','finger':'(奇安信代码卫士)'},
    '奇安信网神安全网络管控平台':{'value':'guankong','finger':'(奇安信网神安全网络管控平台)'},
    '奇安信威胁分析系统':{'value':'weixiefenxi','finger':'(奇安信威胁分析系统)'},

    ###启明星辰设备
    '天阗工控安全监测与审计系统':{'value':'tiantian','finger':'(天阗工控安全监测与审计系统)'},
    '网御高级持续性威胁检测与管理系统':{'value':'wangyu','finger':'(网御高级持续性威胁检测与管理系统)'},
    '天清WEB应用安全网关':{'value':'tianqing','finger':'(天清WAG)'},
    '高级持续性威胁检测与管理系统':{'value':'tar','finger':'(威胁分析一体机|../../v2/assets/images/apple-touch-icon.png)'},
    '网御Web应用安全防护系统':{'value':'wangyu','finger':'(网御Web应用安全防护系统|../../v2/assets/images/apple-touch-icon.png)'},
    '网御VPN':{'value':'wangyu','finger':'(vpn/common/js/leadsec.js|/vpn/user/common/custom/auth_home.css)'},
    '天清汉马VPN':{'value':'tianqinghanma','finger':'(/vpn/common/js/jquery.sslvpn.js)'},
    '网御运维安全网关':{'value':'wangguan','finger':'(/media/stylesheet/nsfocus_2012/images/logo/login_logo_rsas_zh_CN.png|NSFOCUS RSAS)'},
    '天玥网络安全审计系统-互联网行为管控':{'value':'tianyue','finger':'(天玥网络安全审计系统)'},
    '应用交付控制系统(负载均衡)':{'value':'fuzaijunheng','finger':'(ADC)'},
    '弱口令核查系统':{'value':'ruokouling','finger':'(弱口令核查系统)'},
    '4A平台企业版':{'value':'4a','finger':'(4A统一安全管控平台)'},
    '数据库脱敏DBMasking':{'value':'dbmasking','finger':'(数据库脱敏系统-登录)'},
    '异常流量清洗系统(新版本)':{'value':'liuliang','finger':'(天清异常流量管理与抗拒绝服务系统)'},
    '异常流量清洗系统(N系列Guard)':{'value':'liuliang','finger':'(/website/script/login.js)'},
    '天玥运维安全网关':{'value':'tianyue','finger':'(天玥运维安全网关)'},
    '信息安全等级保护检查工具箱':{'value':'gongjuxiang','finger':'(信息安全等级保护检查工具箱管理系统)'},
    '天镜脆弱性扫描与管理系统-工控系统专用版':{'value':'lousao','finger':'(天镜脆弱性扫描与管理系统)'},
    '网御漏洞扫描系统-工控系统专用版':{'value':'lousao','finger':'(网御漏洞扫描系统工控系统专用版)'},
    '网御工控系统安全等级保护检查工具':{'value':'jiancha','finger':'(网御工控系统安全等级保护检查工具)'},
    '网御web漏扫':{'value':'lousao','finger':'(网御web应用检测系统)'},
    '网御漏洞扫描系统(三合一)':{'value':'lousao','finger':'(网御漏洞扫描系统)'},
    '天镜网络非法接入检查系统':{'value':'jiancha','finger':'(天镜脆弱性扫描与管理系统V6.0 网络非法接入检查专版)'},
    '网御网站安全监测平台(新)|天镜网站安全监测平台 (新)':{'value':'jiance','finger':'(网站监测平台)'},
    '网御Leadsec IPS集中管理中心|天清NGIPS集中管理中心':{'value':'ips','finger':'(IPS|/logonprocess.action)'},
    '天清物联网安全接入防护系统(IoT-VBox)':{'value':'iot','finger':'(北京启明星辰信息安全技术有限公司 物联网安全接入防护系统)'},
    '网御工业防火墙(IFW-3000)':{'value':'IFW-3000','finger':'(北京网御星云信息技术有限公司 工业防火墙)'},
    '天清汉马USG-P安全网关609版本|网御安全网关系统609版本|T系列防火墙':{'value':'usg','finger':'(../js/jquery/jsencrypt.min.js)'},
    'FlowEye安全域流监控系统':{'value':'floweye','finger':'(FlowEye安全域流监控系统)'},
    '视频安全防护系统（VSG）大屏展示':{'value':'vsg','finger':'(大屏展示中心)'},
    '网御WAF集中管理中心':{'value':'waf','finger':'(网御WAF)'},
    '天清SWAF_网页防篡改':{'value':'fangcuangai','finger':'(天清Web应用安全网关网页防篡改系统)'},
    '网御SWAF_网页防篡改':{'value':'fangcuangai','finger':'(网御web应用安全防护系统)'},
    '天阗/网御威胁分析一体机(TAR)SP3版本':{'value':'tar','finger':'(CyberSensor)'},
    '天阗/网御威胁分析一体机(TAR)SP1版本':{'value':'uts','finger':'(威胁分析一体机)'},
    '网御APT':{'value':'apt','finger':'(网御高级持续性威胁检测与管理系统)'},

    #海康威视
    '海康威视视频监控':{'value':'hikvision','finger':'(Hikvision Digital Technology Co.|999357577)'},
    'iVMS-8300 安防集成平台':{'value':'hikvision','finger':'(iVMS-8300 安防集成平台)'},
    '综合安防集中监管平台':{'value':'hikvision','finger':'(综合安防集中监管平台)'},
    '海康威视网盘':{'value':'hikvision','finger':'(powered by 海康威视)'},
    '视频编码接入网关':{'value':'hikvision','finger':'(视频编码接入网关)'},
    #大华
    '大华DSS':{'value':'dahua','finger':'(全面提升的安防新平台)'},
    #宇视科技
    '转码服务器配置管理系统':{'value':'unv','finger':'(转码服务器配置管理系统)'},
    '视频监控系统':{'value':'unv','finger':'(软件版本： VM2500-IMOS110-B3305P06)'},
    '公安图像应用平台':{'value':'unv','finger':'(公安图像应用平台)'},
    '云眼':{'value':'unv','finger':'(css/cloudeye-landing.css)'},
    'ISC3500-EL录像机':{'value':'unv','finger':'(ISC3500-EL)'},
    'ISC5000-S':{'value':'unv','finger':'(ISC5000-S)'},
    '可视化报警管理平台':{'value':'unv','finger':'(VM8500-IMOS110-B3323)'},
    '综合安防应用平台':{'value':'unv','finger':'(综合安防应用平台)'},
    #华为
    '华为IBMC':{'value':'huawei','finger':'(/bmc/resources/images/product/img_01.png)'},
    #其它网络设备
    '锐捷产品（Ruijie）':{'value':'ruijie','finger':'(4008 111 000)'},
    'TOTOLink路由器':{'value':'totolink','finger':'(window.location.href="/home.asp")'},
}